fever = OrderSetItem.create!(name: "Treatment for Fever", description: "Generally indicates a need for investigation")
  physician = OrderSetItem.create!(name: "Physician visit", description: "Physician needs to document the symptoms and patient complaints", parent_id: fever.id)
  lab = OrderSetItem.create!(name: "Lab work", description: "Blood and urine tests for diagnosis", parent_id: fever.id)
    blood = OrderSetItem.create!(name: "Blood work", description: "Various blood tests", parent_id: lab.id)
    cbc = OrderSetItem.create!(name: "CBC", description: "Complete blood count", parent_id: blood.id)
    rbc = OrderSetItem.create!(name: "RBC", description: "Red blood cound", parent_id: lab.id)
